Add more validation checks and error handling in all bash scripts.

diff --git a/concat_vids b/concat_vids
--- a/concat_vids
+++ b/concat_vids
@@ -3,10 +3,10 @@
 SCRIPT_DIR="$(realpath "$(dirname "${0}")")"
 
 
-if [ $# -lt 2 ];
-then
-  printf "\nExpected at least two arguments (vid filenames)\n"
-  exit 1
+if [ $# -lt 2 ]; then
+  echo "Expected at least two arguments (vid filenames)" >&2
+  exit 2
+  # https://stackoverflow.com/questions/18568706/check-number-of-arguments-passed-to-a-bash-script
 fi
 
 
@@ -15,12 +15,14 @@ fi
 for VAR in "$@"
 do
   FILE_PATH="$(realpath "${VAR}")"
-  if [[ -e "${FILE_PATH}" ]];
-  then
-    :
+  if [[ -e "${FILE_PATH}" ]]; then
+    if [[ -d "${FILE_PATH}" ]]; then
+      echo "Input path ${VAR} not valid. Must be file, not directory." >&2
+      exit 2
+    fi
   else
-    printf "\nInput file ${FILE_PATH} cannot be found.\n"
-    exit 1
+    echo "Input file ${VAR} cannot be found." >&2
+    exit 2
   fi
 done
 
@@ -29,12 +31,10 @@ done
 FILE_1_DIR="$(realpath "$(dirname "${1}")")"
 LIST_FILE="${FILE_1_DIR}/input_vid_list.txt"
 # Make sure it doesn't exist already
-if [[ -e "${LIST_FILE}" ]] || [[ -h "${LIST_FILE}" ]];
-then
+if [[ -e "${LIST_FILE}" ]] || [[ -h "${LIST_FILE}" ]]; then
   printf "\nTarget file $(basename "${LIST_FILE}") exists in ${FILE_1_DIR}. Overwrite? [Y/N]\n"
   read -p ">" answer
-  if [ "${answer}" == "y" -o "${answer}" == "Y" ];
-  then
+  if [ "${answer}" == "y" -o "${answer}" == "Y" ]; then
     rm "${LIST_FILE}"
   else
     printf "Exiting\n"
@@ -44,8 +44,7 @@ fi
 
 printf "\nEnter new filename (no extension) for combined video (or nothing for default)\n"
 read -p ">" OUTPUT_NAME
-if [ "${OUTPUT_NAME}" == "" ];
-then
+if [ "${OUTPUT_NAME}" == "" ]; then
   # default to modification of first input file's name
   FILENAME_1="$(basename "${1}")"
   FILENAME_1_NO_EXT="${FILENAME_1%.*}"
@@ -54,12 +53,12 @@ fi
 
 OUTPUT_FILEPATH="${FILE_1_DIR}/${OUTPUT_NAME}.mp4"
 
-if [[ -e "${OUTPUT_FILEPATH}" ]] || [[ -h "${OUTPUT_FILEPATH}" ]];
-then
+# Check for existence of output file before attempting conversion.
+# Check for both resolvable path and broken symlink # https://unix.stackexchange.com/a/550837
+if [[ -e "${OUTPUT_FILEPATH}" ]] || [[ -h "${OUTPUT_FILEPATH}" ]]; then
   printf "\nTarget file $(basename "${OUTPUT_FILEPATH}") exists. Overwrite? [Y/N]\n"
   read -p ">" answer
-  if [ "${answer}" == "y" -o "${answer}" == "Y" ];
-  then
+  if [ "${answer}" == "y" -o "${answer}" == "Y" ]; then
     rm "${OUTPUT_FILEPATH}"
   else
     printf "Exiting\n"
@@ -79,10 +78,8 @@ ffmpeg -f concat -safe 0 -i "${LIST_FILE}" -c copy "${OUTPUT_FILEPATH}" &> /dev/
 # https://stackoverflow.com/a/11175851
 
 CONCAT_RETURN=$?
-if [[ ${CONCAT_RETURN} == 0 ]];
-then
-	if [[ -f "${LIST_FILE}" ]];
-	then
+if [[ ${CONCAT_RETURN} == 0 ]]; then
+	if [[ -f "${LIST_FILE}" ]]; then
     # Remove temporary file containing list of input videos.
 		rm "${LIST_FILE}"
 		printf "SUCCESS\n"
diff --git a/convert_vid_to_gif b/convert_vid_to_gif
--- a/convert_vid_to_gif
+++ b/convert_vid_to_gif
@@ -20,35 +20,37 @@ FILE_DIR_OG="$(realpath "$(dirname "${FILE_PATH}")")"
 
 NEW_EXT="gif"
 # put timestamps in output filename
-if [[ $# == 2 ]];
-then
+if [[ $# == 1 ]]; then
+  FILEPATH_OUT="${FILEPATH_NO_EXT}.${NEW_EXT}"
+elif [[ $# == 2 ]]; then
   FILEPATH_OUT="${FILEPATH_NO_EXT}_${2}s-.${NEW_EXT}"
-elif [[ $# == 3 ]];
-then
+elif [[ $# == 3 ]]; then
   FILEPATH_OUT="${FILEPATH_NO_EXT}_${2}-${3}s.${NEW_EXT}"
 else
-  FILEPATH_OUT="${FILEPATH_NO_EXT}.${NEW_EXT}"
+  echo "Expected between 1 and 3 arguments (input file and optional timestamps)" >&2
+  exit 2
+  # https://stackoverflow.com/questions/18568706/check-number-of-arguments-passed-to-a-bash-script
 fi
 
 # Validate input path
-if [[ -e "${FILE_PATH}" ]];
-then
-  :
+if [[ -e "${FILE_PATH}" ]]; then
+  if [[ -d "${FILE_PATH}" ]]; then
+    echo "Input path ${1} not valid. Must be file, not directory." >&2
+    exit 2
+  fi
 else
-  printf "\nSpecified file cannot be found.\n"
-  exit 1
+  echo "Input file ${1} cannot be found." >&2
+  exit 2
 fi
 
 # Check for existence of output file before attempting conversion.
 # ffmpeg has this check, but it requires the rest of the verbose output
 # (which is suppressed below)
 # Check for both resolvable path and broken symlink # https://unix.stackexchange.com/a/550837
-if [[ -e "${FILEPATH_OUT}" ]] || [[ -h "${FILEPATH_OUT}" ]];
-then
+if [[ -e "${FILEPATH_OUT}" ]] || [[ -h "${FILEPATH_OUT}" ]]; then
   printf "\nTarget file $(basename ${FILEPATH_OUT}) exists. Overwrite? [Y/N]\n"
   read -p ">" answer
-  if [ "${answer}" == "y" -o "${answer}" == "Y" ];
-  then
+  if [ "${answer}" == "y" -o "${answer}" == "Y" ];   then
     rm "${FILEPATH_OUT}"
   else
     printf "Exiting\n"
@@ -56,15 +58,8 @@ then
   fi
 fi
 
-if [ $# -gt 3 ];
-then
-  printf "\nExpected one to three arguments - filename, start time (optional), and end time (optional)\n"
-  exit 1
-fi
-
 printf "\nAttempting to convert to gif..."
-if [[ $# == 1 ]]; # one arg
-then
+if [[ $# == 1 ]]; then # one arg
   ### high quality/size:
   # ffmpeg -i "${FILE_PATH}" \
   # -vf "split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse" \
@@ -78,8 +73,7 @@ then
   # -loop 0 "${FILEPATH_OUT}" &> /dev/null
   # https://superuser.com/questions/556029/how-do-i-convert-a-video-to-gif-using-ffmpeg-with-reasonable-quality
   # https://www.ubuntubuzz.com/2017/08/convert-mp4-webm-video-to-gif-using-ffmpeg.html
-elif [[ $# == 2 ]]; # two args
-then
+elif [[ $# == 2 ]]; then # two args
   ### high quality/size:
   # ffmpeg -i "${FILE_PATH}" \
   # -vf "split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse" \
@@ -91,8 +85,7 @@ then
   # ffmpeg -i "${FILE_PATH}" \
   # -vf "fps=10,scale=320:-1:flags=lanczos,split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse" \
   # -loop 0 -ss ${2} "${FILEPATH_OUT}" &> /dev/null
-elif [[ $# == 3 ]]; # three args
-then
+elif [[ $# == 3 ]]; then # three args
   ### high quality/size:
   # ffmpeg -i "${FILE_PATH}" \
   # -vf "split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse" \
@@ -108,13 +101,11 @@ fi
 
 # Test if conversion was successful since ffmpeg output suppressed.
 FFMPEG_RETURN=$? # gets return value of last command executed.
-if [ ${FFMPEG_RETURN} == 0 ]
-then
+if [ ${FFMPEG_RETURN} == 0 ]; then
   # transcribe EXIF comment, if present
   "${SCRIPT_DIR}"/transfer_exif_comment "${FILE_PATH}" "${FILEPATH_OUT}" &> /dev/null
   COMMENT_RETURN=$? # gets return value of last command executed.
-  if [ ${COMMENT_RETURN} == 0 ];
-  then
+  if [ ${COMMENT_RETURN} == 0 ]; then
     printf "SUCCESS\n"
   else
     printf "FAIL\nEXIF-comment transfer unsuccessful.\n"
diff --git a/convert_webp b/convert_webp
--- a/convert_webp
+++ b/convert_webp
@@ -5,17 +5,27 @@
 source "$(realpath "$(dirname "${0}")")/dir_names.sh" # brings in WEBP2GIF_DIR
 # https://stackoverflow.com/questions/59895/how-can-i-get-the-source-directory-of-a-bash-script-from-within-the-script-itsel
 
-if [[ -e "${1}" ]];
-then
-  :
-else
-  printf "\nInput file ${1} cannot be found.\n"
-  exit 1
+if [[ $# -ne 1 ]]; then
+	echo "Expected one argument: img path." >&2
+	exit 2
+  # https://stackoverflow.com/questions/18568706/check-number-of-arguments-passed-to-a-bash-script
 fi
 
 STARTING_DIR="${PWD}"
 FILE_PATH="$(realpath "${1}")"
 # https://code-maven.com/bash-absolute-path
+
+# Validate input path
+if [[ -e "${FILE_PATH}" ]]; then
+  if [[ -d "${FILE_PATH}" ]]; then
+    echo "Input path ${1} not valid. Must be file, not directory." >&2
+    exit 2
+  fi
+else
+  echo "Input file ${1} cannot be found." >&2
+  exit 2
+fi
+
 FILEPATH_NO_EXT="${FILE_PATH%.*}"
 EXT="${FILE_PATH##*.}"
 FILENAME=$(basename "${FILE_PATH}") # includes extension
@@ -25,19 +35,33 @@ FILENAME_NO_EXT=$(basename "${FILE_PATH}" "."${EXT})
 # https://linuxhandbook.com/basename/
 FILE_DIR_OG="$(realpath "$(dirname "${FILE_PATH}")")"
 # https://linuxhandbook.com/dirname/
+FILENAME_GIF="${FILENAME_NO_EXT}.gif"
+
+# Check for existence of output file before attempting conversion.
+# Check for both resolvable path and broken symlink # https://unix.stackexchange.com/a/550837
+FILEPATH_GIF_TARGET="${FILE_DIR_OG}/${FILENAME_GIF}"
+if [[ -e "${FILEPATH_GIF_TARGET}" ]] || [[ -h "${FILEPATH_GIF_TARGET}" ]]; then
+  printf "\nTarget file $(basename ${FILEPATH_GIF_TARGET}) exists. Overwrite? [Y/N]\n"
+  read -p ">" answer
+  if [ "${answer}" == "y" -o "${answer}" == "Y" ];   then
+    rm "${FILEPATH_GIF_TARGET}"
+  else
+    printf "Exiting\n"
+    exit 1
+  fi
+fi
+
 
 # Try using webp2gif first. Will fail if static img
 cp "${FILE_PATH}" "${WEBP2GIF_DIR}"
 cd "${WEBP2GIF_DIR}"
-FILENAME_GIF="${FILENAME_NO_EXT}.gif"
 printf "\nAttempting to convert to animated gif..."
 ./webp2gif "${FILENAME}" "${FILENAME_GIF}" &> /dev/null
 # https://stackoverflow.com/questions/617182/how-can-i-suppress-all-output-from-a-command-using-bash
 WEBP2GIF_RETURN=$? # gets return value of last command executed.
 
 # If webp2gif conversion failed, assume it's a static image.
-if [ ${WEBP2GIF_RETURN} == 0 ]
-then
+if [ ${WEBP2GIF_RETURN} == 0 ]; then
   printf "SUCCESS\n"
   mv "${FILENAME_GIF}" "${FILE_DIR_OG}" # overwrites any existing file w/ same name and ext.
 else
@@ -46,8 +70,7 @@ else
   FILEPATH_JPG="${FILEPATH_NO_EXT}.${NEW_EXT}"
   convert "${FILE_PATH}" "${FILEPATH_JPG}" &> /dev/null
   CONVERT_RETURN=$? # gets return value of last command executed.
-  if [ ${CONVERT_RETURN} == 0 ]
-  then
+  if [ ${CONVERT_RETURN} == 0 ]; then
     printf "SUCCESS\n"
   else
     printf "Static conversion failed too!\n"
diff --git a/extract_vid_frames b/extract_vid_frames
--- a/extract_vid_frames
+++ b/extract_vid_frames
@@ -1,9 +1,14 @@
 #!/bin/bash
 
-# Extract all frames from a given video of GIF w/ optional start and end time
+# Extract all frames from a given video or GIF w/ optional start and end time
 # Works w/ WEBM, MP4, MOV, and GIF input formats (at least)
 # Start and end time can either be integers or in "00:00.00" format
 
+if [[ $# -ne 1 ]]; then
+	echo "Expected one argument: vid path." >&2
+	exit 2
+  # https://stackoverflow.com/questions/18568706/check-number-of-arguments-passed-to-a-bash-script
+fi
 
 
 FILE_PATH="$(realpath "${1}")"
@@ -18,10 +23,21 @@ FILENAME_NO_EXT=$(basename "${FILE_PATH}" "."${EXT})
 FILE_DIR_OG="$(realpath "$(dirname "${FILE_PATH}")")"
 # https://linuxhandbook.com/dirname/
 
+
+# Validate input path
+if [[ -e "${FILE_PATH}" ]]; then
+  if [[ -d "${FILE_PATH}" ]]; then
+    echo "Input path ${1} not valid. Must be file, not directory." >&2
+    exit 2
+  fi
+else
+  echo "Input file ${1} cannot be found." >&2
+  exit 2
+fi
+
 # Create "frames" directory to store output
 OUTPUT_FOLDER="${FILE_DIR_OG}/frames/"
-if [ -d "${OUTPUT_FOLDER}" ];
-then
+if [ -d "${OUTPUT_FOLDER}" ]; then
 	: # do nothing
 else
 	mkdir "${OUTPUT_FOLDER}"
@@ -35,33 +51,26 @@ FILEPATH_OUT="${OUTPUT_FOLDER}/${FILENAME_NO_EXT::20}_%05d.jpg"
 
 # Output-file collisions not handled
 
-if [[ $# -gt 3 ]];
-then
-  printf "\nExpected one to three arguments - filename, start time (optional), and end time (optional)\n"
-  exit 1
-fi
-
 printf "\nAttempting to extract video frames..."
-if [[ $# == 1 ]]; # one arg
-then
+if [[ $# == 1 ]]; then # one arg
   # Extract frames from entire vid
   ffmpeg -i "${FILE_PATH}" -qscale:v 2 "${FILEPATH_OUT}" &> /dev/null
   # https://stackoverflow.com/questions/10957412/fastest-way-to-extract-frames-using-ffmpeg
   # https://stackoverflow.com/questions/10225403/how-can-i-extract-a-good-quality-jpeg-image-from-a-video-file-with-ffmpeg/10234065#10234065
   # https://stackoverflow.com/questions/617182/how-can-i-suppress-all-output-from-a-command-using-bash
-elif [[ $# == 2 ]]; # two args
-then
+elif [[ $# == 2 ]]; then # two args
   # Extract all frames from given timestamp to end.
   ffmpeg -ss ${2} -i "${FILE_PATH}" -qscale:v 2 "${FILEPATH_OUT}" &> /dev/null
-elif [[ $# == 3 ]]; # three args
-then
+elif [[ $# == 3 ]]; then # three args
   ffmpeg -i "${FILE_PATH}" -qscale:v 2  -ss ${2} -to ${3} "${FILEPATH_OUT}" &> /dev/null
+else
+  echo "Expected between 1 and 3 arguments (input file and optional timestamps)" >&2
+  exit 2
 fi
 
 # Test if conversion was successful since ffmpeg output suppressed.
 FFMPEG_RETURN=$? # gets return value of last command executed.
-if [ ${FFMPEG_RETURN} == 0 ]
-then
+if [ ${FFMPEG_RETURN} == 0 ]; then
   FRAME_COUNT=$(find "${OUTPUT_FOLDER}" -maxdepth 1 -type f|wc -l)
   # https://stackoverflow.com/a/11132110
   printf "SUCCESS - ${FRAME_COUNT} frames\n"
diff --git a/gif_patrol_cyc b/gif_patrol_cyc
--- a/gif_patrol_cyc
+++ b/gif_patrol_cyc
@@ -5,6 +5,13 @@
 # Works w/ GIF, WEBM, MP4, MOV input formats (at least)
 # Start and end time can either be integers or in "00:00.00" format
 
+if [[ $# -ne 1 ]]; then
+	echo "Expected one argument: gif/vid path." >&2
+	exit 2
+  # https://stackoverflow.com/questions/18568706/check-number-of-arguments-passed-to-a-bash-script
+fi
+
+
 STARTING_DIR="${PWD}"
 SCRIPT_DIR="$(realpath "$(dirname "${0}")")"
 FILE_PATH="$(realpath "${1}")"
@@ -19,44 +26,40 @@ FILENAME_NO_EXT=$(basename "${FILE_PATH}" "."${EXT})
 FILE_DIR_OG="$(realpath "$(dirname "${FILE_PATH}")")"
 # https://linuxhandbook.com/dirname/
 
-
-if [ $# -gt 3 ];
-then
-  printf "\nExpected one to three arguments - filename, start time (optional), and end time (optional)\n"
-  exit 1
-fi
 # Validate input path
-if [[ -e "${FILE_PATH}" ]];
-then
-  :
+if [[ -e "${FILE_PATH}" ]]; then
+  if [[ -d "${FILE_PATH}" ]]; then
+    echo "Input path ${1} not valid. Must be file, not directory." >&2
+    exit 2
+  fi
 else
-  printf "\nSpecified file cannot be found.\n"
-  exit 1
+  echo "Input file ${1} cannot be found." >&2
+  exit 2
+  # https://stackoverflow.com/questions/18568706/check-number-of-arguments-passed-to-a-bash-script
 fi
 
 
 NEW_EXT="gif"
 # put timestamps in output filename
-if [[ $# == 2 ]];
-then
+if [[ $# == 1 ]]; then
+  FILEPATH_OUT="${FILEPATH_NO_EXT}_pcyc.${NEW_EXT}"
+elif [[ $# == 2 ]]; then
   FILEPATH_OUT="${FILEPATH_NO_EXT}_${2}s-_pcyc.${NEW_EXT}"
-elif [[ $# == 3 ]];
-then
+elif [[ $# == 3 ]]; then
   FILEPATH_OUT="${FILEPATH_NO_EXT}_${2}-${3}s_pcyc.${NEW_EXT}"
 else
-  FILEPATH_OUT="${FILEPATH_NO_EXT}_pcyc.${NEW_EXT}"
+  echo "Expected between 1 and 3 arguments (input file and optional timestamps)" >&2
+  exit 2
 fi
 
 # Check for existence of output file before attempting conversion.
 # ffmpeg has this check, but it requires the rest of the verbose output
 # (which is suppressed below)
 # Check for both resolvable path and broken symlink # https://unix.stackexchange.com/a/550837
-if [[ -e "${FILEPATH_OUT}" ]] || [[ -h "${FILEPATH_OUT}" ]];
-then
+if [[ -e "${FILEPATH_OUT}" ]] || [[ -h "${FILEPATH_OUT}" ]]; then
   printf "\nTarget file $(basename "${FILEPATH_OUT}") exists. Overwrite? [Y/N]\n"
   read -p ">" answer
-  if [ "${answer}" == "y" -o "${answer}" == "Y" ];
-  then
+  if [ "${answer}" == "y" -o "${answer}" == "Y" ]; then
     rm "${FILEPATH_OUT}"
   else
     printf "Exiting\n"
@@ -66,8 +69,7 @@ fi
 
 # Create temp directory to store output
 TEMP_FOLDER="${FILE_DIR_OG}/gif_temp/"
-if [ -d "${TEMP_FOLDER}" ];
-then
+if [ -d "${TEMP_FOLDER}" ]; then
 	: # do nothing
 else
 	mkdir "${TEMP_FOLDER}"
@@ -80,27 +82,23 @@ TEMP_PATH_NOEXT="${TEMP_FOLDER}/${FILENAME_NO_EXT}"
 
 # Collisions in temp files not handled
 
-if [[ $# == 1 ]]; # one arg
-then
+if [[ $# == 1 ]]; then # one arg
   # If not already a gif, convert to gif first. Case-insensitive comparison:
-  if [[ "${EXT,,}" == "${NEW_EXT,,}" ]]; # https://stackoverflow.com/a/27679748
-  then
+  if [[ "${EXT,,}" == "${NEW_EXT,,}" ]]; then # https://stackoverflow.com/a/27679748
     printf "\nAttempting to create patrol-cycle gif..."
 
     convert "${FILE_PATH}" -coalesce -duplicate 1,-2-1 -quiet \
     -layers OptimizePlus -loop 0 "${FILEPATH_OUT}" &> /dev/null
   else
     INTER_GIF_PATH="${TEMP_PATH%.*}.${NEW_EXT}"
-    if [[ -e "${INTER_GIF_PATH}" ]];
-    then
+    if [[ -e "${INTER_GIF_PATH}" ]]; then
       rm "${INTER_GIF_PATH}"
     fi
 
     printf "\nAttempting to convert/trim to gif format..."
     "${SCRIPT_DIR}"/convert_vid_to_gif "${TEMP_PATH}" &> /dev/null
     GIF_CONVERT_RETURN=$? # gets return value of last command executed.
-    if [ ${GIF_CONVERT_RETURN} == 0 ];
-    then
+    if [ ${GIF_CONVERT_RETURN} == 0 ]; then
       printf "SUCCESS\nAttempting to create patrol-cycle gif..."
 
       convert "${INTER_GIF_PATH}" -coalesce -duplicate 1,-2-1 -quiet \
@@ -114,22 +112,18 @@ then
     fi
   fi
 
-elif [[ $# == 2 ]]; # two args
-then
+elif [[ $# == 2 ]]; then # two args
   # If not already a gif, convert to gif first. Case-insensitive comparison:
-  if [[ "${EXT,,}" == "${NEW_EXT,,}" ]]; # https://stackoverflow.com/a/27679748
-  then
+  if [[ "${EXT,,}" == "${NEW_EXT,,}" ]]; then # https://stackoverflow.com/a/27679748
     INTER_GIF_PATH="${TEMP_PATH_NOEXT}_${2}s-.gif"
-    if [[ -e "${INTER_GIF_PATH}" ]];
-    then
+    if [[ -e "${INTER_GIF_PATH}" ]]; then
       rm "${INTER_GIF_PATH}"
     fi
 
     printf "\nAttempting to trim..."
     "${SCRIPT_DIR}"/trim_only "${TEMP_PATH}" ${2} &> /dev/null
     TRIM_RETURN=$? # gets return value of last command executed.
-    if [ ${TRIM_RETURN} == 0 ];
-    then
+    if [ ${TRIM_RETURN} == 0 ]; then
       printf "SUCCESS\nAttempting to create patrol-cycle gif..."
 
       convert "${INTER_GIF_PATH}" -coalesce -duplicate 1,-2-1 -quiet \
@@ -141,16 +135,14 @@ then
     fi
   else
     INTER_GIF_PATH="${TEMP_PATH_NOEXT}_${2}s-.gif"
-    if [[ -e "${INTER_GIF_PATH}" ]];
-    then
+    if [[ -e "${INTER_GIF_PATH}" ]]; then
       rm "${INTER_GIF_PATH}"
     fi
 
     printf "\nAttempting to convert/trim to gif format..."
     "${SCRIPT_DIR}"/convert_vid_to_gif "${TEMP_PATH}" ${2} &> /dev/null
     GIF_CONVERT_RETURN=$? # gets return value of last command executed.
-    if [ ${GIF_CONVERT_RETURN} == 0 ];
-    then
+    if [ ${GIF_CONVERT_RETURN} == 0 ]; then
       printf "SUCCESS\nAttempting to create patrol-cycle gif..."
 
       convert "${INTER_GIF_PATH}" -coalesce -duplicate 1,-2-1 -quiet \
@@ -161,22 +153,18 @@ then
       exit 1
     fi
   fi
-elif [[ $# == 3 ]]; # three args
-then
+elif [[ $# == 3 ]]; then # three args
   # If not already a gif, convert to gif first. Case-insensitive comparison:
-  if [[ "${EXT,,}" == "${NEW_EXT,,}" ]]; # https://stackoverflow.com/a/27679748
-  then
+  if [[ "${EXT,,}" == "${NEW_EXT,,}" ]]; then # https://stackoverflow.com/a/27679748
     INTER_GIF_PATH="${TEMP_PATH_NOEXT}_${2}-${3}s.gif"
-    if [[ -e "${INTER_GIF_PATH}" ]];
-    then
+    if [[ -e "${INTER_GIF_PATH}" ]]; then
       rm "${INTER_GIF_PATH}"
     fi
 
     printf "\nAttempting to trim..."
     "${SCRIPT_DIR}"/trim_only "${TEMP_PATH}" ${2} ${3} &> /dev/null
     TRIM_RETURN=$? # gets return value of last command executed.
-    if [ ${TRIM_RETURN} == 0 ];
-    then
+    if [ ${TRIM_RETURN} == 0 ]; then
       printf "SUCCESS\nAttempting to create patrol-cycle gif..."
 
       convert "${INTER_GIF_PATH}" -coalesce -duplicate 1,-2-1 -quiet \
@@ -188,8 +176,7 @@ then
     fi
   else
     INTER_GIF_PATH="${TEMP_PATH_NOEXT}_${2}-${3}s.gif"
-    if [[ -e "${INTER_GIF_PATH}" ]];
-    then
+    if [[ -e "${INTER_GIF_PATH}" ]]; then
       rm "${INTER_GIF_PATH}"
     fi
 
@@ -197,8 +184,7 @@ then
     printf "\nAttempting to convert/trim to gif format..."
     "${SCRIPT_DIR}"/convert_vid_to_gif "${TEMP_PATH}" ${2} ${3} &> /dev/null
     GIF_CONVERT_RETURN=$? # gets return value of last command executed.
-    if [ ${GIF_CONVERT_RETURN} == 0 ];
-    then
+    if [ ${GIF_CONVERT_RETURN} == 0 ]; then
       printf "SUCCESS\nAttempting to create patrol-cycle gif..."
 
       convert "${INTER_GIF_PATH}" -coalesce -duplicate 1,-2-1 -quiet \
@@ -213,13 +199,11 @@ fi
 
 # Test if conversion was successful since ffmpeg output suppressed.
 PATROL_CYC_RETURN=$? # gets return value of last command executed.
-if [ ${PATROL_CYC_RETURN} == 0 ]
-then
+if [ ${PATROL_CYC_RETURN} == 0 ]; then
   # transcribe EXIF comment, if present
   "${SCRIPT_DIR}"/transfer_exif_comment "${FILE_PATH}" "${FILEPATH_OUT}" &> /dev/null
   COMMENT_RETURN=$? # gets return value of last command executed.
-  if [ ${COMMENT_RETURN} == 0 ];
-  then
+  if [ ${COMMENT_RETURN} == 0 ]; then
     printf "SUCCESS\n"
   else
     printf "FAIL\nEXIF-comment transfer unsuccessful.\n"
diff --git a/transfer_exif_comment b/transfer_exif_comment
--- a/transfer_exif_comment
+++ b/transfer_exif_comment
@@ -1,17 +1,39 @@
 #!/bin/bash
 
+if [[ $# -ne 2 ]]; then
+	echo "Expected two arguments: img/vid paths." >&2
+	exit 2
+  # https://stackoverflow.com/questions/18568706/check-number-of-arguments-passed-to-a-bash-script
+fi
+
+# Validate input path
+FILE_PATH_1="$(realpath "${1}")"
+FILE_PATH_2="$(realpath "${2}")"
+if [[ -e "${FILE_PATH_1}" ]] && [[ -e "${FILE_PATH_1}" ]]; then
+  if [[ -d "${FILE_PATH_1}" ]]; then
+	  echo "Input path ${1} not valid. Must be file, not directory." >&2
+	  exit 2
+	elif [[ -d "${FILE_PATH_2}" ]]; then
+		echo "Input path ${2} not valid. Must be file, not directory." >&2
+		exit 2
+	fi
+else
+  echo "Input file ${1} cannot be found." >&2
+  exit 2
+fi
+
+
 SCRIPT_DIR="$(realpath "$(dirname "${0}")")"
 # Temporarily switch working directory to script location to call python
 cd "${SCRIPT_DIR}"
-python <<< "import format_convert as fc ; fc.transfer_exif_comment('${1}', '${2}')"
+python <<< "import format_convert as fc ; fc.transfer_exif_comment('${FILE_PATH_1}', '${FILE_PATH_2}')"
 # https://unix.stackexchange.com/questions/533156/using-python-in-a-bash-script
 cd - > /dev/null # suppress outputs
 
 
 PYTHON_RETURN=$? # gets return value of last command executed.
 # Make sure the program ran correctly
-if [ ${PYTHON_RETURN} -ne 0 ]
-then
+if [ ${PYTHON_RETURN} -ne 0 ]; then
 	printf "\nSomething went wrong when transferring EXIF comment.\n"
 	exit 1
 fi
diff --git a/trim_only b/trim_only
--- a/trim_only
+++ b/trim_only
@@ -1,9 +1,8 @@
 #!/bin/bash
 
 # Trim a given video (or GIF) according to specified start and (optional) end timestamp.
-# Output is in mp4 format.
-# If neither timestamp specified, can be used to just convert input vid to mp4 format.
-# works w/ WEBM, MP4, MOV, and GIF input formats (at least)
+# Output is in source format.
+# Works w/ WEBM, MP4, MOV, and GIF input formats (at least)
 # Start and end time can either be integers or in "00:00.00" format
 SCRIPT_DIR="$(realpath "$(dirname "${0}")")"
 FILE_PATH="$(realpath "${1}")"
@@ -20,39 +19,37 @@ FILE_DIR_OG="$(realpath "$(dirname "${FILE_PATH}")")"
 
 NEW_EXT="${EXT,,}" # convert to lowercase for caller functions to correctly predict naming # https://stackoverflow.com/a/2264537
 # put timestamps in output filename
-if [[ $# == 2 ]];
-then
+if [[ $# == 2 ]]; then
   FILEPATH_OUT="${FILEPATH_NO_EXT}_${2}s-.${NEW_EXT}"
-elif [[ $# == 3 ]];
-then
+elif [[ $# == 3 ]]; then
   FILEPATH_OUT="${FILEPATH_NO_EXT}_${2}-${3}s.${NEW_EXT}"
 else
-  FILEPATH_OUT="${FILEPATH_NO_EXT}.${NEW_EXT}"
+  echo "Expected between 2 and 3 arguments (input file, start timestamp, and optional end timestamp)" >&2
+  exit 2
+  # https://stackoverflow.com/questions/18568706/check-number-of-arguments-passed-to-a-bash-script
 fi
 
 # Validate input path
-if [[ -e "${FILE_PATH}" ]];
-then
-  :
+if [[ -e "${FILE_PATH}" ]]; then
+  if [[ -d "${FILE_PATH}" ]]; then
+	  echo "Input path ${1} not valid. Must be file, not directory." >&2
+	  exit 2
+	fi
 else
-  printf "\nSpecified file cannot be found.\n"
-  exit 1
+  echo "Input file ${1} cannot be found." >&2
+  exit 2
+  # https://stackoverflow.com/questions/18568706/check-number-of-arguments-passed-to-a-bash-script
 fi
 
-# Check for existence of output file before attempting conversion.
+
+# Check for existence of output file before attempting trim.
 # ffmpeg has this check, but it requires the rest of the verbose output
 # (which is suppressed below)
 # Check for both resolvable path and broken symlink # https://unix.stackexchange.com/a/550837
-if [[ $# -lt 2 ]]; # no timestamps specified.
-then
-  printf "\nExpected at least two arguments - filename, start time, and end time (optional)\n"
-  exit 1
-elif [[ -e "${FILEPATH_OUT}" ]] || [[ -h "${FILEPATH_OUT}" ]];
-then
-  printf "\nTarget file $(basename ${FILEPATH_OUT}) exists. Overwrite? [Y/N]\n"
+if [[ -e "${FILEPATH_OUT}" ]] || [[ -h "${FILEPATH_OUT}" ]]; then
+  printf "\nTarget file $(basename "${FILEPATH_OUT}") exists. Overwrite? [Y/N]\n"
   read -p ">" answer
-  if [ "${answer}" == "y" -o "${answer}" == "Y" ];
-  then
+  if [ "${answer}" == "y" -o "${answer}" == "Y" ]; then
     rm "${FILEPATH_OUT}"
   else
     printf "Exiting\n"
@@ -60,11 +57,6 @@ then
   fi
 fi
 
-if [[ $# -gt 3 ]];
-then
-  printf "\nExpected up to three arguments - filename, start time, and end time (optional)\n"
-  exit 1
-fi
 
 printf "\nAttempting to trim..."
 if [[ $# == 2 ]]; # two args
@@ -77,13 +69,11 @@ fi
 
 # Test if conversion was successful since ffmpeg output suppressed.
 FFMPEG_RETURN=$? # gets return value of last command executed.
-if [ ${FFMPEG_RETURN} == 0 ]
-then
+if [ ${FFMPEG_RETURN} == 0 ]; then
   # transcribe EXIF comment, if present
   "${SCRIPT_DIR}"/transfer_exif_comment "${FILE_PATH}" "${FILEPATH_OUT}" &> /dev/null
   COMMENT_RETURN=$? # gets return value of last command executed.
-  if [ ${COMMENT_RETURN} == 0 ];
-  then
+  if [ ${COMMENT_RETURN} == 0 ]; then
     printf "SUCCESS\n"
   else
     printf "FAIL\nEXIF-comment transfer unsuccessful.\n"
diff --git a/trim_to_mp4 b/trim_to_mp4
--- a/trim_to_mp4
+++ b/trim_to_mp4
@@ -20,39 +20,43 @@ FILE_DIR_OG="$(realpath "$(dirname "${FILE_PATH}")")"
 
 NEW_EXT="mp4"
 # put timestamps in output filename
-if [[ $# == 2 ]];
-then
+if [[ $# == 1 ]]; then
+  FILEPATH_OUT="${FILEPATH_NO_EXT}.${NEW_EXT}"
+elif [[ $# == 2 ]]; then
   FILEPATH_OUT="${FILEPATH_NO_EXT}_${2}s-.${NEW_EXT}"
-elif [[ $# == 3 ]];
-then
+elif [[ $# == 3 ]]; then
   FILEPATH_OUT="${FILEPATH_NO_EXT}_${2}-${3}s.${NEW_EXT}"
 else
-  FILEPATH_OUT="${FILEPATH_NO_EXT}.${NEW_EXT}"
+  echo "Expected between 1 and 3 arguments (input file and optional timestamps)" >&2
+  exit 2
+  # https://stackoverflow.com/questions/18568706/check-number-of-arguments-passed-to-a-bash-script
 fi
 
 # Validate input path
-if [[ -e "${FILE_PATH}" ]];
-then
-  :
+if [[ -e "${FILE_PATH}" ]]; then
+  if [[ -d "${FILE_PATH}" ]]; then
+	  echo "Input path ${1} not valid. Must be file, not directory." >&2
+	  exit 2
+	fi
 else
-  printf "\nSpecified file cannot be found.\n"
-  exit 1
+  echo "Input file ${1} cannot be found." >&2
+  exit 2
+  # https://stackoverflow.com/questions/18568706/check-number-of-arguments-passed-to-a-bash-script
 fi
+
 
 # Check for existence of output file before attempting conversion.
 # ffmpeg has this check, but it requires the rest of the verbose output
 # (which is suppressed below)
 # Check for both resolvable path and broken symlink # https://unix.stackexchange.com/a/550837
-if [[ ${FILE_PATH} == ${FILEPATH_OUT} ]]; # trivial case of mp4 input file w/ no timestamps passed.
-then
-  printf "\nOutput file cannot have same name as input file.\n"
-  exit 1
-elif [[ -e "${FILEPATH_OUT}" ]] || [[ -h "${FILEPATH_OUT}" ]];
-then
+if [[ ${FILE_PATH} == ${FILEPATH_OUT} ]]; then # trivial case of mp4 input file w/ no timestamps passed.
+  echo "\nOutput file cannot have same name as input file." >&2
+  exit 2
+  # https://stackoverflow.com/questions/18568706/check-number-of-arguments-passed-to-a-bash-script
+elif [[ -e "${FILEPATH_OUT}" ]] || [[ -h "${FILEPATH_OUT}" ]]; then
   printf "\nTarget file $(basename ${FILEPATH_OUT})  exists. Overwrite? [Y/N]\n"
   read -p ">" answer
-  if [ "${answer}" == "y" -o "${answer}" == "Y" ];
-  then
+  if [ "${answer}" == "y" -o "${answer}" == "Y" ]; then
     rm "${FILEPATH_OUT}"
   else
     printf "Exiting\n"
@@ -60,38 +64,29 @@ then
   fi
 fi
 
-if [[ $# -gt 3 ]];
-then
-  printf "\nExpected one to three arguments - filename, start time (optional), and end time (optional)\n"
-  exit 1
-fi
 
 printf "\nAttempting to trim/convert..."
-if [[ $# == 1 ]]; # one arg
-then
+if [[ $# == 1 ]]; then # one arg
   # The utility of this case is a simple format conversion to mp4
-  ffmpeg -i "${FILE_PATH}" -movflags faststart \
+  ffmpeg -i "${FILE_PATH}" -movflags +faststart \
             "${FILEPATH_OUT}" &> /dev/null
   # https://stackoverflow.com/questions/617182/how-can-i-suppress-all-output-from-a-command-using-bash
-elif [[ $# == 2 ]]; # two args
-then
-  ffmpeg -ss ${2} -i "${FILE_PATH}" -movflags faststart \
+elif [[ $# == 2 ]]; then # two args
+  ffmpeg -ss ${2} -i "${FILE_PATH}" -movflags +faststart \
                      "${FILEPATH_OUT}" &> /dev/null
-elif [[ $# == 3 ]]; # three args
-then
-  ffmpeg -i "${FILE_PATH}" -ss ${2} -to ${3} -movflags faststart \
-                     "${FILEPATH_OUT}" &> /dev/null
+elif [[ $# == 3 ]]; then # three args
+  ffmpeg -ss ${2} -to ${3} -i "${FILE_PATH}" -movflags +faststart \
+                              "${FILEPATH_OUT}" &> /dev/null
 fi
+# https://stackoverflow.com/questions/25569180/ffmpeg-convert-without-loss-quality
 
 # Test if conversion was successful since ffmpeg output suppressed.
 FFMPEG_RETURN=$? # gets return value of last command executed.
-if [ ${FFMPEG_RETURN} == 0 ]
-then
+if [ ${FFMPEG_RETURN} == 0 ]; then
   # transcribe EXIF comment, if present
   "${SCRIPT_DIR}"/transfer_exif_comment "${FILE_PATH}" "${FILEPATH_OUT}" &> /dev/null
   COMMENT_RETURN=$? # gets return value of last command executed.
-  if [ ${COMMENT_RETURN} == 0 ];
-  then
+  if [ ${COMMENT_RETURN} == 0 ]; then
     printf "SUCCESS\n"
   else
     printf "FAIL\nEXIF-comment transfer unsuccessful.\n"
diff --git a/write_exif_comment b/write_exif_comment
--- a/write_exif_comment
+++ b/write_exif_comment
@@ -1,22 +1,25 @@
 #!/bin/bash
 
 
-if [ $# -ne 2 ];
-then
-  printf "\nExpected two arguments - filename and comment to add\n"
-  exit 1
+if [ $# -ne 2 ]; then
+  echo "Expected two arguments - filename and comment to add" >&2
+  exit 2
+  # https://stackoverflow.com/questions/18568706/check-number-of-arguments-passed-to-a-bash-script
 fi
 
 
 FILE_PATH="$(realpath "${1}")"
 COMMENT="${2}"
 # Validate input path
-if [[ -e "${FILE_PATH}" ]];
-then
-  :
+if [[ -e "${FILE_PATH}" ]]; then
+  if [[ -d "${FILE_PATH}" ]]; then
+	  echo "Input path ${1} not valid. Must be file, not directory." >&2
+	  exit 2
+	fi
 else
-  printf "\nSpecified file cannot be found.\n"
-  exit 1
+  echo "Input file ${1} cannot be found." >&2
+  exit 2
+  # https://stackoverflow.com/questions/18568706/check-number-of-arguments-passed-to-a-bash-script
 fi
 
 # Does not check for existence of a comment first
@@ -25,10 +28,8 @@ exiftool -Comment="${COMMENT}" "${FILE_PATH}" &> /dev/null
 EXIF_RETURN=$?
 OG_BU_PATH="${FILE_PATH}_original"
 
-if [[ ${EXIF_RETURN} == 0 ]];
-then
-	if [[ -f "${OG_BU_PATH}" ]];
-	then
+if [[ ${EXIF_RETURN} == 0 ]]; then
+	if [[ -f "${OG_BU_PATH}" ]]; then
 		rm "${OG_BU_PATH}"
 		printf "SUCCESS\n"
 	else
