Improve transfer_exif_comment file-exist checks.

diff --git a/transfer_exif_comment b/transfer_exif_comment
--- a/transfer_exif_comment
+++ b/transfer_exif_comment
@@ -9,16 +9,21 @@ fi
 # Validate input path
 FILE_PATH_1="$(realpath "${1}")"
 FILE_PATH_2="$(realpath "${2}")"
-if [[ -e "${FILE_PATH_1}" ]] && [[ -e "${FILE_PATH_1}" ]]; then
-  if [[ -d "${FILE_PATH_1}" ]]; then
+if [[ -e "${FILE_PATH_1}" ]]; then
+	if [[ -d "${FILE_PATH_1}" ]]; then
 	  echo "Input path ${1} not valid. Must be file, not directory." >&2
 	  exit 2
+else
+  echo "Input file ${1} cannot be found." >&2
+  exit 2
+fi
+if [[ -e "${FILE_PATH_2}" ]]; then
 	elif [[ -d "${FILE_PATH_2}" ]]; then
 		echo "Input path ${2} not valid. Must be file, not directory." >&2
 		exit 2
 	fi
 else
-  echo "Input file ${1} cannot be found." >&2
+  echo "Input file ${2} cannot be found." >&2
   exit 2
 fi
 
